-- AlterTable
ALTER TABLE `order` ADD COLUMN `change_amount` INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN `discount` INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN `money_received` INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN `note` VARCHAR(191) NULL,
    ADD COLUMN `payment_method` VARCHAR(191) NOT NULL DEFAULT 'CASH',
    ADD COLUMN `status` VARCHAR(191) NOT NULL DEFAULT 'COMPLETED';
